###
GET http://localhost:3000/api/v1/user HTTP/1.1


###
POST http://localhost:3000/api/v1/user HTTP/1.1
content-type: application/json

{
    "name": "Daniel T",
    "email": "daniel11234@el.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "daniel1234@el.com",
    "password": "123456"
}



###
PUT http://localhost:3000 HTTP/1.1
Content-Type: : application/json

{}

###
DELETE http://localhost:3000 HTTP/1.1